services:
  - type: web
    name: plantcare-inference
    runtime: docker
    plan: 1c-2g
    dockerfilePath: ./api/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeployTrigger: "off"
    envVars:
      - key: PORT
        value: 8000
