import 'dart:io';import 'package:flutter/material.dart';import 'package:image_picker/image_picker.dart';import '../../core/app_services.dart';import '../../core/models/plant.dart';import '../../core/navigation/app_router.dart';import '../../core/theme/app_theme.dart';
class ScannerScreen extends StatefulWidget{const ScannerScreen({super.key});@override State<ScannerScreen> createState()=>_ScannerScreenState();}
class _ScannerScreenState extends State<ScannerScreen>{late Future<List<Plant>> plants;String? selectedId;String? imagePath;String? error;bool analyzing=false;final picker=ImagePicker();@override void initState(){super.initState();plants=load();}Future<List<Plant>> load()async{final p=await AppServices.garden.getPlants();if(selectedId==null&&p.isNotEmpty)selectedId=p.first.id;return p;}Plant? selected(List<Plant> p)=>p.where((x)=>x.id==selectedId).firstOrNull;
Future<void> pick(ImageSource source)async{if(analyzing)return;final x=await picker.pickImage(source:source,imageQuality:90,maxWidth:2048,maxHeight:2048);if(x!=null)setState((){imagePath=x.path;error=null;});}
Future<void> analyze()async{if(imagePath==null){setState(()=>error='Choose a photo first.');return;}final p=await plants;final plant=selected(p);if(plant==null){setState(()=>error='Add a plant before scanning.');return;}setState((){analyzing=true;error=null;});try{final u=await AppServices.auth.currentUser();if(u==null)throw StateError('Sign in required.');final ref=await AppServices.imageStorage.uploadPlantImage(filePath:imagePath!,userId:u.id);final result=await AppServices.diagnosis.diagnose(imagePath:imagePath!,imageReference:ref,plantId:plant.id,plantHint:plant.name);if(mounted)Navigator.pushNamed(context,AppRouter.diagnosis,arguments:result);}catch(_){if(mounted)setState(()=>error='We could not analyze this photo. Try a clearer image.');}finally{if(mounted)setState(()=>analyzing=false);}}
@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:FutureBuilder<List<Plant>>(future:plants,builder:(c,s){if(s.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());final p=s.data??const <Plant>[];final plant=selected(p);return ListView(padding:const EdgeInsets.fromLTRB(16,10,16,24),children:[
Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Scan',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),Text('AI plant health check',style:TextStyle(color:PlantCareColors.muted))])),IconButton(tooltip:'Health history',onPressed:()=>Navigator.pushNamed(c,AppRouter.diagnosisHistory),icon:const Icon(Icons.history_rounded))]),
const SizedBox(height:16),const Text('SELECT PLANT',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900,letterSpacing:.7,color:PlantCareColors.primary)),const SizedBox(height:8),
if(p.isEmpty)Card(child:ListTile(leading:const Icon(Icons.eco_outlined,color:PlantCareColors.primary),title:const Text('No plants yet',style:TextStyle(fontWeight:FontWeight.w800)),subtitle:const Text('Add a plant so this scan can be saved to your garden.'),trailing:TextButton(onPressed:()=>Navigator.pushNamed(c,AppRouter.addPlant),child:const Text('ADD'))) else DropdownButtonFormField<String>(initialValue:plant?.id,decoration:const InputDecoration(prefixIcon:Icon(Icons.eco_outlined),hintText:'Choose from My Plants'),items:[for(final x in p)DropdownMenuItem(value:x.id,child:Text(x.name))],onChanged:analyzing?null:(v)=>setState(()=>selectedId=v)),
const SizedBox(height:18),const Text('PHOTO',style:TextStyle(fontSize:12,fontWeight:FontWeight.w900,letterSpacing:.7,color:PlantCareColors.primary)),const SizedBox(height:8),
Container(height:300,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),border:Border.all(color:PlantCareColors.border)),child:analyzing?const Center(child:Column(mainAxisSize:MainAxisSize.min,children:[CircularProgressIndicator(),SizedBox(height:14),Text('Analyzing plant…',style:TextStyle(fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Checking visual disease signals',style:TextStyle(color:PlantCareColors.muted,fontSize:12))]):imagePath==null?const Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.document_scanner_outlined,size:48,color:PlantCareColors.primary),SizedBox(height:10),Text('Add a clear plant photo',style:TextStyle(fontSize:17,fontWeight:FontWeight.w800)),SizedBox(height:4),Text('Good light • leaf in focus • affected area visible',style:TextStyle(color:PlantCareColors.muted,fontSize:12))]):Stack(fit:StackFit.expand,children:[ClipRRect(borderRadius:BorderRadius.circular(12),child:Image.file(File(imagePath!),fit:BoxFit.cover)),Positioned(top:8,right:8,child:IconButton.filledTonal(onPressed:()=>setState(()=>imagePath=null),icon:const Icon(Icons.close)))])),
if(error!=null)Padding(padding:const EdgeInsets.only(top:8),child:Text(error!,textAlign:TextAlign.center,style:const TextStyle(color:PlantCareColors.danger))),
const SizedBox(height:12),Row(children:[Expanded(child:OutlinedButton.icon(onPressed:analyzing?null:()=>pick(ImageSource.gallery),icon:const Icon(Icons.photo_library_outlined),label:Text(imagePath==null?'Gallery':'Change'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:analyzing?null:()=>pick(ImageSource.camera),icon:const Icon(Icons.camera_alt_outlined),label:Text(imagePath==null?'Camera':'Retake')))]),
if(imagePath!=null&&!analyzing)Padding(padding:const EdgeInsets.only(top:8),child:SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:plant==null?null:analyze,icon:const Icon(Icons.center_focus_strong),label:const Text('ANALYZE PHOTO')))),
const SizedBox(height:8),const Text('PlantCare AI provides an AI-assisted result. Review low-confidence results carefully.',textAlign:TextAlign.center,style:TextStyle(color:PlantCareColors.muted,fontSize:11))]));})),bottomNavigationBar:const AppBottomNav(selectedIndex:2));}
}